export const departamentos = [
	{
		departamento: "Eletrônicos",
		categorias: [
			"Celulares",
			"Notebooks",
			"TVs",
			"Tablets",
			"Smartwatches",
			"Câmeras",
			"Drones",
			"Fones de ouvido",
			"Consoles",
			"Monitores",
			"Impressoras",
			"Carregadores",
			"Baterias",
			"Componentes",
			"Teclados",
			"Mouses",
			"Softwares",
			"Projetores",
			"Roteadores",
			"HDs",
			"SSD",
			"Placas de vídeo",
			"Placas-mãe",
			"Cabos e adaptadores",
		],
	},
	{
		departamento: "Roupas",
		categorias: [
			"Masculino",
			"Feminino",
			"Infantil",
			"Casacos",
			"Camisetas",
			"Calças",
			"Shorts",
			"Saias",
			"Vestidos",
			"Sapatos",
			"Tênis",
			"Sandálias",
			"Chinelos",
			"Acessórios",
			"Meias",
			"Bonés",
			"Moletons",
			"Roupas íntimas",
			"Pijamas",
			"Moda praia",
			"Moda esportiva",
			"Uniformes",
			"Jaquetas",
			"Social",
		],
	},
	{
		departamento: "Casa",
		categorias: [
			"Móveis",
			"Decoração",
			"Utensílios",
			"Eletrodomésticos",
			"Cozinha",
			"Banheiro",
			"Jardinagem",
			"Iluminação",
			"Quadros",
			"Tapetes",
			"Cortinas",
			"Roupa de cama",
			"Colchões",
			"Cadeiras",
			"Sofás",
			"Mesas",
			"Escritório",
			"Organizadores",
			"Prateleiras",
			"Vasos",
			"Ferramentas",
			"Piscinas",
			"Segurança",
			"Aromas",
		],
	},
	{
		departamento: "Esportes",
		categorias: [
			"Futebol",
			"Basquete",
			"Corrida",
			"Tênis",
			"Vôlei",
			"Handebol",
			"Ciclismo",
			"Musculação",
			"Natação",
			"Skate",
			"Esportes radicais",
			"Yoga",
			"Pilates",
			"Ginástica",
			"Surf",
			"Canoagem",
			"Trilhas",
			"Escalada",
			"Patinação",
			"Esqui",
			"Karatê",
			"Jiu-jitsu",
			"Boxe",
			"Pesca",
		],
	},
	{
		departamento: "Beleza",
		categorias: [
			"Maquiagem",
			"Cuidado com a pele",
			"Perfumes",
			"Cabelos",
			"Unhas",
			"Barbearia",
			"Estética",
			"Depilação",
			"Shampoos",
			"Condicionadores",
			"Cremes",
			"Óleos",
			"Esfoliantes",
			"Pincéis",
			"Base",
			"Batom",
			"Sombra",
			"Máscara de cílios",
			"Delineador",
			"Autobronzeador",
			"Protetor solar",
			"Hidratantes",
			"Esponjas",
			"Lentes de contato",
		],
	},
	{
		departamento: "Alimentos",
		categorias: [
			"Bebidas",
			"Snacks",
			"Doces",
			"Carnes",
			"Congelados",
			"Pães",
			"Massas",
			"Laticínios",
			"Vegetais",
			"Frutas",
			"Cereais",
			"Enlatados",
			"Molhos",
			"Temperos",
			"Chocolates",
			"Chás",
			"Cafés",
			"Refrigerantes",
			"Sucos",
			"Águas",
			"Vinhos",
			"Cervejas",
			"Bebidas energéticas",
			"Produtos orgânicos",
		],
	},
	{
		departamento: "Livros",
		categorias: [
			"Ficção",
			"Não-ficção",
			"Autoajuda",
			"Terror",
			"Romance",
			"Fantasia",
			"Filosofia",
			"Psicologia",
			"Ciências",
			"História",
			"Biografias",
			"Clássicos",
			"Suspense",
			"Policial",
			"HQs",
			"Mangás",
			"Infantis",
			"Educação",
			"Religião",
			"Negócios",
			"Investimentos",
			"Arte",
			"Música",
			"Gastronomia",
		],
	},
	{
		departamento: "Brinquedos",
		categorias: [
			"Infantil",
			"Colecionáveis",
			"Jogos",
			"Quebra-cabeças",
			"Pelúcias",
			"Bonecas",
			"Carrinhos",
			"Triciclos",
			"Lego",
			"Blocos de montar",
			"Casinhas",
			"Brinquedos educativos",
			"Jogos de tabuleiro",
			"Cartas",
			"Massinhas",
			"Patinetes",
			"Bicicletas infantis",
			"Fantasias",
			"Dinossauros",
			"Super-heróis",
			"Artes e pintura",
			"Instrumentos musicais",
			"Brinquedos de praia",
			"Drones infantis",
		],
	},
	{
		departamento: "Ferramentas",
		categorias: [
			"Elétricas",
			"Manuais",
			"Jardinagem",
			"Marcenaria",
			"Construção",
			"Ferramentas automotivas",
			"Soldagem",
			"Furadeiras",
			"Parafusadeiras",
			"Serra",
			"Multímetros",
			"Trenas",
			"Escadas",
			"Cintas de amarração",
			"Chaves de fenda",
			"Alicates",
			"Compressores",
			"Betoneiras",
			"Pistolas de pintura",
			"Martelos",
			"Brocas",
			"Lixas",
			"Rebitadores",
			"Engrenagens",
		],
	},
	{
		departamento: "Saúde",
		categorias: [
			"Medicamentos",
			"Suplementos",
			"Higiene",
			"Primeiros socorros",
			"Equipamentos médicos",
			"Cuidado com os olhos",
			"Cuidado com os ouvidos",
			"Ortopedia",
			"Fisioterapia",
			"Exames médicos",
			"Termômetros",
			"Pressão arterial",
			"Diabetes",
			"Vitaminas",
			"Óleos essenciais",
			"Máscaras",
			"Aromaterapia",
			"Produtos veganos",
			"Hidratantes",
			"Curativos",
			"Protetores solares",
			"Repelentes",
			"Higiene bucal",
			"Bem-estar mental",
		],
	},
]
