name: Desafio Avanti

on:
    push:
        branches: [main]

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            - name: Setup Node
              uses: actions/setup-node@v4
              with:
                  node-version: 20.x

            - name: Install and build desenvolvimento-do-layout
              run: |
                  cd desenvolvimento-do-layout
                  npm install
                  npm run build

            - name: Install and build buscar-de-perfil-do-github
              run: |
                  cd buscar-de-perfil-do-github
                  npm install
                  npm run build

            - name: Deploy to GitHub Pages 01
              uses: peaceiris/actions-gh-pages@v3
              with:
                  github_token: ${{ secrets.GH_TOKEN }}
                  publish_dir: desenvolvimento-do-layout/dist
                  destination_dir: desenvolvimento-do-layout

            - name: Deploy to GitHub Pages 02
              uses: peaceiris/actions-gh-pages@v3
              with:
                  github_token: ${{ secrets.GH_TOKEN }}
                  publish_dir: buscar-de-perfil-do-github/dist
                  destination_dir: buscar-de-perfil-do-github
